x-soloai-volumes:
  &soloai-volumes
  - ${BASE_PATH}/mautic/config:/var/www/html/config:z
  - ${BASE_PATH}/mautic/logs:/var/www/html/var/logs:z
  - ${BASE_PATH}/mautic/media/files:/var/www/html/docroot/media/files:z
  - ${BASE_PATH}/mautic/media/images:/var/www/html/docroot/media/images:z
  - ${BASE_PATH}/cron:/opt/mautic/cron:z
  - mautic-docroot:/var/www/html/docroot:z

services:
  db:
    image: mysql:lts
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes: 
      - ${BASE_PATH}/mysql-data:/var/lib/mysql
      - ./init-strapi-db.sql:/docker-entrypoint-initdb.d/init-strapi-db.sql
    healthcheck:
      test: mysqladmin --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD ping
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - mautic-docroot:/var/www/html/docroot:z
      - ./mautic/media/files:/var/www/html/docroot/media/files:z
      - ./mautic/media/images:/var/www/html/docroot/media/images:z
    depends_on:
      - mautic_web
    ports:
      - 8080:80
    networks:
       - default
  
  mautic_web:
    image: mautic/mautic:6-fpm
    links:
      - db:mysql
    volumes: *soloai-volumes
    environment:
      - DOCKER_MAUTIC_LOAD_TEST_DATA=${DOCKER_MAUTIC_LOAD_TEST_DATA}
      - DOCKER_MAUTIC_RUN_MIGRATIONS=${DOCKER_MAUTIC_RUN_MIGRATIONS}
    env_file:
      - .mautic_env
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default

  mautic_cron:
    image: mautic/mautic:6-fpm
    links:
      - db:mysql
    volumes: *soloai-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_cron
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

  mautic_worker:
    image: mautic/mautic:6-fpm
    links:
      - db:mysql
    volumes: *soloai-volumes
    environment:
      - DOCKER_MAUTIC_ROLE=mautic_worker
    env_file:
      - .mautic_env
    depends_on:
      mautic_web:
        condition: service_healthy
    networks:
      - default

  strapi:
    image: vshadbolt/strapi
    environment:
      NODE_ENV: development # or production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${MYSQL_HOST}
      DATABASE_PORT: ${MYSQL_PORT}
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: ${MYSQL_STRAPI_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      DATABASE_SSL: false
    ports:
      - "1337:1337"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - strapi-app:/srv/app:z
    networks:
      - default      

volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/mysql-data
      o: bind
  mautic-docroot:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/mautic-docroot
      o: bind
  strapi-app:
    driver: local
    driver_opts:
      type: none
      device: ${BASE_PATH}/strapi
      o: bind

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-docker
